name: dbt CI

on:
  pull_request:
    branches: ["main"]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    environment: ci

  
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    defaults:
      run:
        working-directory: my_project

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Create profiles.yml (ci)
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << 'EOF'
          my_project:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
                user: "{{ env_var('SNOWFLAKE_USER') }}"
                password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
                role: "{{ env_var('SNOWFLAKE_ROLE') }}"
                database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
                warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
                schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
                threads: 4
          EOF

 
      - name: Check required env exists (safe)
        run: |
          test -n "$SNOWFLAKE_ACCOUNT" || (echo "Missing SNOWFLAKE_ACCOUNT" && exit 1)
          test -n "$SNOWFLAKE_USER" || (echo "Missing SNOWFLAKE_USER" && exit 1)
          test -n "$SNOWFLAKE_DATABASE" || (echo "Missing SNOWFLAKE_DATABASE" && exit 1)
          test -n "$SNOWFLAKE_SCHEMA" || (echo "Missing SNOWFLAKE_SCHEMA" && exit 1)

      - name: Show profiles.yml (safe)
        run: |
          sed -e "s/password: .*/password: ***MASKED***/" ~/.dbt/profiles.yml

      - name: dbt deps
        run: dbt deps --profiles-dir ~/.dbt

      - name: dbt debug
        run: dbt debug --profiles-dir ~/.dbt --target ci

      - name: dbt build
        run: dbt build --profiles-dir ~/.dbt --target ci --fail-fast
